import type { InboundInput, Protocol } from '../api/types'

// InboundFormState is the flat UI state; buildInboundInput turns it into the
// API payload (settings_json / stream_settings_json). REALITY keys and the
// Shadowsocks password are generated by the backend, so they are not asked for.
export interface InboundFormState {
  tag: string
  protocol: Protocol
  port: number
  network: 'tcp' | 'ws' | 'grpc'
  security: 'none' | 'tls' | 'reality'
  flow: string
  dest: string
  serverNames: string
  tlsServerName: string
  wsPath: string
  grpcServiceName: string
}

export function emptyInboundForm(): InboundFormState {
  return {
    tag: '',
    protocol: 'vless',
    port: 443,
    network: 'tcp',
    security: 'reality',
    flow: 'xtls-rprx-vision',
    dest: 'www.microsoft.com:443',
    serverNames: 'www.microsoft.com',
    tlsServerName: '',
    wsPath: '/',
    grpcServiceName: 'grpc',
  }
}

export function buildInboundInput(f: InboundFormState): InboundInput {
  const settings: Record<string, unknown> = {}
  if (f.protocol === 'vless' && f.security === 'reality') settings.flow = f.flow

  const stream: Record<string, unknown> = { network: f.network, security: f.security }
  if (f.security === 'reality') {
    stream.reality = {
      dest: f.dest,
      server_names: f.serverNames.split(',').map((s) => s.trim()).filter(Boolean),
    }
  } else if (f.security === 'tls') {
    stream.tls = { server_name: f.tlsServerName }
  }
  if (f.network === 'ws') stream.ws = { path: f.wsPath }
  if (f.network === 'grpc') stream.grpc = { service_name: f.grpcServiceName }

  return {
    tag: f.tag,
    protocol: f.protocol,
    port: f.port,
    enabled: true,
    settings_json: settings,
    stream_settings_json: stream,
  }
}
